### ISSUE TITLE
[FEA]: Upgrade to PyTorch 2+

### ISSUE THREAD

**Issue by mdemoret-nv** [nv-morpheus/Morpheus#1008]
### Is this a new feature, an improvement, or a change to existing functionality?

Improvement

### How would you describe the priority of this feature request

Medium

### Please provide a clear description of problem this feature solves

To enable Hopper support (with `sm_90`) we need to upgrade to PyTorch 2.0+ with CUDA 11.8.

### Describe your ideal solution

The PR for this issue should include:

1. Test whether or not we can install PyTorch via Conda
   1. Currently we use pip to install PyTorch since there was no overlap between the version of CUDA they required and our own version of CUDA. With the latest PyTorch, they now support CUDA 11.8 which is our current version.
1. Upgrade to the latest available PyTorch that works with our set of dependencies
1. Update any code that had breaking changes due to the transition from PyTorch 1.13 -> 2.0+
   1. This should include any examples such as the GNN example

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the [open feature requests](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22%2Cimprovement%2Cenhancement) and have found no duplicates for this feature request

**Comment by jarmak-nv** [comment]
Open Q: while doing this, does it make sense to default the torch memory pool [to use RMM](https://github.com/rapidsai/rmm/blob/branch-23.08/README.md#using-rmm-with-pytorch)? Reducing memory usage when combining torch with cuDF is always a win.

Happy to open this discussion in a different place, just figured it might be efficient while we're touching torch anyway.

**Comment by mdemoret-nv** [comment]
@jarmak-nv That is interesting and certainly something we should explore, but I think that we should break this up into two issues. Using the RMM allocator has other benefits too (We could then directly access PyTorch tensors from C++ like we do with cuDF). Exploring those possibilities would be outside of the scope of a simple version upgrade.

**Comment by jarmak-nv** [comment]
Thought that might be the case, I'll open an issue so we can prioritize and work on as we see fit.
