### ISSUE TITLE
[FEA]: GitHub Issue Form Installation Method update

### ISSUE THREAD

**Issue by nvawood** [nv-morpheus/Morpheus#1109]
### Is this a new feature, an improvement, or a change to existing functionality?

Improvement

### How would you describe the priority of this feature request

Low (would be nice)

### Please provide a clear description of problem this feature solves

When creating a new Issue in GitHub the available installation method options do not include an option for NGC (or Kubernetes). 

### Describe your ideal solution

Adding an option to select NGC or (generically) Kubernetes would allow some bug reports to be more accurate.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the [open feature requests](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22%2Cimprovement%2Cenhancement) and have found no duplicates for this feature request

**Comment by jarmak-nv** [comment]
Hi @nvawood!
  
  Thanks for submitting this issue - our team has been notified and we'll get back to you as soon as we can!
  In the mean time, feel free to add any relevant information to this issue.
