### ISSUE TITLE
[DOC]: Some minor corrections for some of the examples README

### ISSUE THREAD

**Issue by pdmack** [nv-morpheus/Morpheus#1128]
### How would you describe the priority of this documentation request

Medium

### Please provide a link or source to the relevant docs

https://github.com/nv-morpheus/Morpheus/tree/branch-23.11/examples

### Describe the problems in the documentation

Some of the docs for the examples assumes a morpheus developer environment but certain paths are not correct inside the runtime container.

https://github.com/nv-morpheus/Morpheus/blob/branch-23.11/examples/abp_nvsmi_detection/README.md?plain=1#L104

Inside the container there is no concept of MORPHEUS_ROOT. It could mean `/workspace` or `/opt/conda/envs/morpheus/lib/python3.10/site-packages/` the latter obviously being counter-intuitive.

https://github.com/nv-morpheus/Morpheus/blob/branch-23.11/examples/digital_fingerprinting/starter/README.md?plain=1#L163 in a few spots in the pipeline CLI.

https://github.com/nv-morpheus/Morpheus/blob/branch-23.11/examples/log_parsing/README.md?plain=1#L66

### (Optional) Propose a correction

Possibly just specify that all these files should be read from the models dir.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the [open documentation issues](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Adoc) and have found no duplicates for this bug report

**Comment by efajardo-nv** [comment]
Closing this because`MORPHEUS_ROOT` has since been removed from these examples in subsequent releases.
