### ISSUE TITLE
[FEA]: Add Milvus vector DB service and sink

### ISSUE THREAD

**Issue by mdemoret-nv** [nv-morpheus/Morpheus#1177]
### Is this a new feature, an improvement, or a change to existing functionality?

New Feature

### How would you describe the priority of this feature request

High

### Please provide a clear description of problem this feature solves

To enable Morpheus to work with Vector databases (VDB), often used with LLM and RAG, a Milvus service and sink should be added. This would allow Morpheus to not only query VDBs in pipelines, but also use Morpheus pipelines to seed VDBs to be used else where.

Milvus has been chosen since it is the most commonly supported VDB between the 3 major LLM libraries: Langchain, llama-index, and Haystack.

### Describe your ideal solution

This new feature should include two main components: a service and a sink. The service should function outside of the pipeline and act as a common point to interact with the database. The sink should allow messages to be directly written into the database. The sink will be a user of the service.

Key functionality that is required:

- Milvus Service
  - Capable of configuring access to the database
  - Ability to fetch records from the VDB with optional parameters
  - Ability to write documents to the VDB
  - Capable of reading/writing simultaneously from multiple threads
- Milvus Sink
  - Capable of converting Morpheus messages into the native Milvus format
  - Utilizes the Milvus service to perform the actual writes

### Additional context

Utilize the existing implementations in popular LLM libraries for inspiration:

- Llamaindex: https://gpt-index.readthedocs.io/en/latest/examples/vector_stores/MilvusIndexDemo.html
- Haystack: https://haystack.deepset.ai/integrations/milvus-document-store

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the [open feature requests](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22%2Cimprovement%2Cenhancement) and have found no duplicates for this feature request

**Comment by mdemoret-nv** [comment]
Note: We may want to consider other Vector DB implementations if Haystack is deprecating support for Milvus: https://github.com/deepset-ai/haystack/discussions/4771

**Comment by bsuryadevara** [comment]
@mdemoret-nv It seems that Qdrant can work with a set of libraries listed below. I will study these APIs to understand them better and check if there are any significant differences when compared to the Milvus Vector DataStore.
![image](https://github.com/nv-morpheus/Morpheus/assets/4812413/cf0578d7-7410-4920-b529-549d118f0064)
