### ISSUE TITLE
[FEA]: Create a 'skip-ci' label

### ISSUE THREAD

**Issue by dagardner-nv** [nv-morpheus/Morpheus#1183]
### Is this a new feature, an improvement, or a change to existing functionality?

New Feature

### How would you describe the priority of this feature request

Low (would be nice)

### Please provide a clear description of problem this feature solves

Per our new workflows we are opening draft PRs at the start of development, rather than at the end. 

To avoid spamming CI with un-needed jobs and devs needing to add `[no-ci]` to commit notes, we would like to have a `skip-ci` label, which when attached to a PR would skip CI until removed.

### Describe your ideal solution

Avoid all CI jobs from running, or minimally bail early in a pre-flight job.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the [open feature requests](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22%2Cimprovement%2Cenhancement) and have found no duplicates for this feature request

**Comment by mdemoret-nv** [comment]
Just to add to this MRC currently has the ability to skip certain stages based on a label on the PR. This could easily be expanded to skip the rest of CI. Should look to MRC for an example implementation
