### ISSUE TITLE
[DOC]: this step seems out of place

### ISSUE THREAD

**Issue by nyck33** [nv-morpheus/Morpheus#1196]
### How would you describe the priority of this documentation request

Medium

### Please provide a link or source to the relevant docs

theReadme

### Describe the problems in the documentation

`./external/utilities/docker/install_docker.sh `

I started the Morpheus container but there is no such script

```
base) nyck33@nyck33-ubuntu2204:/media/mydrive/cybersecurity/Morpheus$ docker run --rm -ti --runtime=nvidia --gpus=all --net=host -v /var/run/docker.sock:/var/run/docker.sock nvcr.io/nvidia/morpheus/morpheus:23.07.02-runtime bash
(morpheus) root@nyck33-ubuntu2204:/workspace# ./external/utilities/docker/install_docker.sh
bash: ./external/utilities/docker/install_docker.sh: No such file or directory
(morpheus) root@nyck33-ubuntu2204:/workspace# ls
CHANGELOG.md  CONTRIBUTING.md  LICENSE  README.md  docker  docs  examples  models  scripts
(morpheus) root@nyck33-ubuntu2204:/workspace# cd docker
(morpheus) root@nyck33-ubuntu2204:/workspace/docker# ls

```

### (Optional) Propose a correction

Add more details for first timers.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the [open documentation issues](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Adoc) and have found no duplicates for this bug report

**Comment by jarmak-nv** [comment]
Hi @nyck33!
  
  Thanks for submitting this issue - our team has been notified and we'll get back to you as soon as we can!
  In the mean time, feel free to add any relevant information to this issue.
