### ISSUE TITLE
[DOC]: Bind the provided abp-pcap-xgb directory to the docker container model repo at /models.

### ISSUE THREAD

**Issue by nyck33** [nv-morpheus/Morpheus#1201]
### How would you describe the priority of this documentation request

Medium

### Please provide a link or source to the relevant docs

https://github.com/nv-morpheus/Morpheus/blob/branch-23.11/examples/abp_pcap_detection/README.md

### Describe the problems in the documentation

I'm not sure what that means, I see the abp-pcap-xgb directory but not a docker container model repo at /models.

### (Optional) Propose a correction

Please try to be a bit more clear.  

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the [open documentation issues](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Adoc) and have found no duplicates for this bug report

**Comment by jarmak-nv** [comment]
Hi @nyck33!
  
  Thanks for submitting this issue - our team has been notified and we'll get back to you as soon as we can!
  In the mean time, feel free to add any relevant information to this issue.

**Comment by efajardo-nv** [comment]
@nyck33 it's referring to `-v $PWD/abp-pcap-xgb:/models/abp-pcap-xgb` in the `docker run` command which will mount the `abp-pcap-xgb` directory to `/models/abp-pcap-xgb` in the Triton container. The `/models` directory  in the Triton container acts as the model repository from which models are loaded. We can reword that to make it more clear. Thanks.
