### ISSUE TITLE
[BUG]: Wrong outputs from PreprocessFILStage

### ISSUE THREAD

**Issue by efajardo-nv** [nv-morpheus/Morpheus#1250]
### Version

23.11

### Which installation method(s) does this occur on?

Docker

### Describe the bug.

In the process of migrating our 22.11 pipeline to 23.07, we noticed that results are now different. Upon investigating we found the source of the discrepancy was the output the `PreprocessFILStage`, both the C++ and Python versions. We noticed in 22.11, the cpp PreprocessFILStage creates a c_contiguous array, while the python version creates a f_continguous array. This can be resolved in the 23.07 Python version (`preprocess_fil_stage.py`) by changing:
```
data = cp.asarray([df.to](http://df.to/)_cupy()) 
```
to
```
data = cp.ascontiguousarray([df.to_cupy()).
```

Issue still exists when running pipeline in 23.11.

### Code of Conduct

- [X] I agree to follow Morpheus' Code of Conduct
- [X] I have searched the [open bugs](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by mdemoret-nv** [comment]
Fixed by #1390
