### ISSUE TITLE
[BUG]: cloned twice and missing .devcontainer folder

### ISSUE THREAD

**Issue by nyck33** [nv-morpheus/Morpheus#1254]
### Version

23.11

### Describe the bug.

Tried ```MORPHEUS_ROOT=$(pwd)/morpheus
git clone https://github.com/nv-morpheus/Morpheus.git $MORPHEUS_ROOT
cd $MORPHEUS_ROOT``` as suggested here: https://github.com/nv-morpheus/Morpheus/blob/branch-23.11/docs/source/getting_started.md

and missing .devcontainer folder.

First time I did `git clone git@github.com:nv-morpheus/Morpheus.git` and that time it was also missing the .git folder.

### Minimum reproducible example

```shell
I have no idea
```

### Relevant log output

<details><summary>Click here to see error details</summary><pre>

 [Paste the error here, it will be hidden by default]

</pre></details>

### Full env printout

not applicable?

### Code of Conduct

- [X] I agree to follow Morpheus' Code of Conduct
- [X] I have searched the [open bugs](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by jarmak-nv** [comment]
Hi @nyck33!
  
  Thanks for submitting this issue - our team has been notified and we'll get back to you as soon as we can!
  In the mean time, feel free to add any relevant information to this issue.

**Comment by nyck33** [comment]
It happend again with the provided commands on the Get Started page.

**Comment by mdemoret-nv** [comment]
@nyck33 Can you see any of the directories that start with a period? There should be 5: `.devcontainer`, `.github`, `.gitlab`, `.git` and `.tmp`.

Can you output the contents of the Morpheus root directory?
```
cd $MORPHEUS_ROOT
ls
```
