### ISSUE TITLE
[BUG]: DFP Azure output path/filename is hardcoded

### ISSUE THREAD

**Issue by pthalasta** [nv-morpheus/Morpheus#1287]
### Version

23.11

### Which installation method(s) does this occur on?

Source

### Describe the bug.

DFP Azure pipeline currently has hardcoded value for output and doesn't have an option to customize the path when invoking with `python`. This needs to be considered as an input parameter with default path to allow customization on where the output is written and the format of the file

### Relevant log output

<details><summary>Click here to see error details</summary><pre>

 [Paste the error here, it will be hidden by default]

</pre></details>

### Full env printout

<details><summary>Click here to see environment details</summary><pre>

 [Paste the results of print_env.sh here, it will be hidden by default]

</pre></details>

### Code of Conduct

- [X] I agree to follow Morpheus' Code of Conduct
- [X] I have searched the [open bugs](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by mdemoret-nv** [comment]
The property `filename` for the `WriteToFileStage` needs to come from a click option.
