### ISSUE TITLE
[BUG]: Milvus 2.3.2 is breaking milvus_vector_db_service tests

### ISSUE THREAD

**Issue by bsuryadevara** [nv-morpheus/Morpheus#1345]
### Version

fea-sherlock

### Which installation method(s) does this occur on?

Source

### Describe the bug.

milvus==2.3.2 is breaking milvus_vector_db_service tests. Where as it works with `2.3.1`

```
    @pytest.mark.milvus
    def test_delete_by_keys(milvus_service: MilvusVectorDBService,
                            idx_part_collection_config: dict,
                            milvus_data: list[dict]):
        collection_name = "test_delete_by_keys_collection"
    
        # Make sure to drop any existing collection from previous runs.
        milvus_service.drop(collection_name)
    
        # Create a collection.
        milvus_service.create(collection_name, **idx_part_collection_config)
    
        # Insert data into the collection.
        milvus_service.insert(collection_name, milvus_data)
    
        # Delete data by keys from the collection.
        keys_to_delete = [5, 6]
        response = milvus_service.delete_by_keys(collection_name, keys_to_delete)
>       assert response == keys_to_delete
E       assert [] == [5, 6]
E         Right contains 2 more items, first extra item: 5
E         Use -v to get more diff
```

### Relevant log output

<details><summary>Click here to see error details</summary><pre>

 [Paste the error here, it will be hidden by default]

</pre></details>

### Full env printout

<details><summary>Click here to see environment details</summary><pre>

 [Paste the results of print_env.sh here, it will be hidden by default]

</pre></details>

### Code of Conduct

- [X] I agree to follow Morpheus' Code of Conduct
- [X] I have searched the [open bugs](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by cwharris** [comment]
Closed by #1348
