### ISSUE TITLE
[DOC]: Morpheus Examples link to symlinks

### ISSUE THREAD

**Issue by pranavm7** [nv-morpheus/Morpheus#1356]
### How would you describe the priority of this documentation request

Medium

### Please provide a link or source to the relevant docs

https://github.com/nv-morpheus/Morpheus/blob/branch-23.11/docs/source/examples.md

### Describe the problems in the documentation

Possible side effect of #536, the links within the [Morpheus Examples](https://github.com/nv-morpheus/Morpheus/tree/branch-23.11#using-morpheus) document link to respective symlinks located at [docs/source/examples](https://github.com/nv-morpheus/Morpheus/tree/branch-23.11/docs/source/examples). 
However, the symlinks link to respective docs within the [examples](https://github.com/nv-morpheus/Morpheus/blob/branch-23.11/docs/source/examples.md) folder. This approach makes the documentation a bit difficult to read as github doesn't render symlinks, and feels a bit redundant, therefore I would like to report it as a bug.

### (Optional) Propose a correction

Update links in [this](https://github.com/nv-morpheus/Morpheus/blob/branch-23.11/docs/source/examples.md) file from `./examples/__example_model__/README.md` to `../../examples/__example_model__/README.md`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the [open documentation issues](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Adoc) and have found no duplicates for this bug report

**Comment by jarmak-nv** [comment]
Hi @pranavm7!
  
  Thanks for submitting this issue - our team has been notified and we'll get back to you as soon as we can!
  In the mean time, feel free to add any relevant information to this issue.

**Comment by pranavm7** [comment]
It is a pretty simple fix! I would like to create a PR with the same  :)
