### ISSUE TITLE
[FEA] Use SRF's log handler

### ISSUE THREAD

**Issue by dagardner-nv** [nv-morpheus/Morpheus#137]
**Is your feature request related to a problem? Please describe.**
Newer versions of Neo/SRF add a custom log handler `neo.core.log_handler.NeoHandler`
This allows us to forward Python logs to Neo's C++ logger allowing all logs to end up in the same destinations.

This also allows us to control the log severity of Neo's logger via `NeoHandler.setLevel`

**Comment by mdemoret-nv** [comment]
Closing since this has already been implemented.
