### ISSUE TITLE
[DOC]: cloudtrail-ae pipeline args need updating

### ISSUE THREAD

**Issue by pdmack** [nv-morpheus/Morpheus#1405]
### How would you describe the priority of this documentation request

High

### Please provide a link or source to the relevant docs

https://github.com/nv-morpheus/Morpheus/blob/branch-23.11/docs/source/cloud_deployment_guide.md?plain=1#L448

### Describe the problems in the documentation

#1398 addressed the validation pipelines but we need a doc update here also

`--timestamp_column_name="event_dt"`

### (Optional) Propose a correction

add args above

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the [open documentation issues](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Adoc) and have found no duplicates for this bug report

**Comment by dagardner-nv** [comment]
Fixed by PR #1406
