### ISSUE TITLE
[DOC]: Can you provide the code that used Python faker to make the Azure DFP datasets?

### ISSUE THREAD

**Issue by nyck33** [nv-morpheus/Morpheus#1410]
### How would you describe the priority of this documentation request

Low (would be nice)

### Describe the future/missing documentation

It says in dfp-feature-selection-demo.ipynb "This notebook includes an introduction to DFP, the suggested steps for DFP feature selection, and the code segments demonstrating how each step can be done in practice.<br>
Note. This notebook uses Azure AD logs as an example but the same process can be applied to any data sources.<br>
<font color='#C00000'>Disclaimer.</font> The data was generated using the python [faker](https://faker.readthedocs.io/en/master/#) package. If there is any resemblance to real individuals, it is purely coincidental." and I want to make more data to train on before I deploy to my own Azure cloud with a web app connected to Azure OpenAI services and Snowflake.  

### Where have you looked?

I did shfit-ctrl-f in VS Code for "faker" and only see it thee and `cuda11.8_dev.yml`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the [open documentation issues](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Adoc) and have found no duplicates for this bug report

**Comment by jarmak-nv** [comment]
Hi @nyck33!
  
  Thanks for submitting this issue - our team has been notified and we'll get back to you as soon as we can!
  In the mean time, feel free to add any relevant information to this issue.

**Comment by efajardo-nv** [comment]
Sorry @nyck33. The code is not available but should not be too difficult to reproduce using faker.

Here's more info about the dataset:
https://github.com/nv-morpheus/Morpheus/blob/branch-24.10/models/datasets/README.md#dfp-azure-logs

Steps to download it from S3:
https://github.com/nv-morpheus/Morpheus/blob/branch-24.10/examples/digital_fingerprinting/production/README.md#steps-to-run-example-pipeline
