### ISSUE TITLE
[QST] 22.06 docker input args

### ISSUE THREAD

**Issue by pdmack** [nv-morpheus/Morpheus#144]
**What is your question?**
Are we planning to update any of the major arguments to the docker release image build?

```
Building morpheus:...
   FROM_IMAGE      : gpuci/miniforge-cuda
   CUDA_VER        : 11.4
   LINUX_DISTRO    : ubuntu
   LINUX_VER       : 20.04
   RAPIDS_VER      : 21.10
   PYTHON_VER      : 3.8
   TENSORRT_VERSION: 8.2.1.3
```

For example, latest TENSORRT8 version is 8.2.5

**Comment by cwharris** [comment]
We will need to update `CUDA_VER` to `11.5` to build against cudf `22.04`.

**Comment by mdemoret-nv** [comment]
As of now, this is the current output:
```
Building morpheus:...
   FROM_IMAGE      : gpuci/miniforge-cuda
   CUDA_VER        : 11.5
   LINUX_DISTRO    : ubuntu
   LINUX_VER       : 20.04
   RAPIDS_VER      : 22.06
   PYTHON_VER      : 3.8
   TENSORRT_VERSION: 8.2.1.3
```

@pdmack Does that work for you?

**Comment by mdemoret-nv** [comment]
Closing this since its been answered and to get it off the 22.06 boards. Reopen if necessary
