### ISSUE TITLE
[BUG]:  DFencoder Model struggles to converge when it is trained solely with numerical features

### ISSUE THREAD

**Issue by spatil44** [nv-morpheus/Morpheus#1455]
### Version

23.11

### Which installation method(s) does this occur on?

Kubernetes

### Describe the bug.

The DFencoder Model struggles to converge when it is trained solely with numerical features, as evidenced by the training and validation loss remaining consistent and not decreasing. However, when a new categorical feature is introduced to the dataset, the model begins to converge, resulting in a noticeable reduction in both training and validation loss.

### Minimum reproducible example

```shell
Use IRIS dataset.
1. Use only numerical features, train dfencoder model observe training and validation loss.
2. Add constant string feature to dataset, train dfencoder model observe training and validation loss
```

### Relevant log output

<details><summary>Click here to see error details</summary><pre>

Attaching training and validation loss with both scenario

</pre></details>
![error](https://github.com/nv-morpheus/Morpheus/assets/122857913/4d3a4782-dbcb-44c0-a022-0048e52a5b3a)

### Full env printout

<details><summary>Click here to see environment details</summary><pre>

 [Paste the results of print_env.sh here, it will be hidden by default]

</pre></details>

### Code of Conduct

- [X] I agree to follow Morpheus' Code of Conduct
- [X] I have searched the [open bugs](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by jarmak-nv** [comment]
Hi @spatil44!
  
  Thanks for submitting this issue - our team has been notified and we'll get back to you as soon as we can!
  In the mean time, feel free to add any relevant information to this issue.
