### ISSUE TITLE
function running into errors when passing 'json' file. 

### ISSUE THREAD

**Issue by ylnhari** [nv-morpheus/Morpheus#1470]
Here https://github.com/nv-morpheus/Morpheus/blob/06bda2d0dd62379273e34a01a8199c50da2e7f5d/morpheus/utils/logger.py#L84

if i replace with 'json' with '.json' , `configure_logging()` function of Morpheus is working else program executes code from `else` even though i provide a valid JSON path ('/home/data/log/log_config.json')

**Comment by jarmak-nv** [comment]
Hi @ylnhari!
  
  Thanks for submitting this issue - our team has been notified and we'll get back to you as soon as we can!
  In the mean time, feel free to add any relevant information to this issue.
