### ISSUE TITLE
[BUG]: testing issue

### ISSUE THREAD

**Issue by yuchenz427** [nv-morpheus/Morpheus#1516]
### Version

24.03

### Which installation method(s) does this occur on?

Docker

### Describe the bug.

testing issue

### Relevant log output

<details><summary>Click here to see error details</summary><pre>

 [Paste the error here, it will be hidden by default]

</pre></details>

### Full env printout

<details><summary>Click here to see environment details</summary><pre>

 [Paste the results of print_env.sh here, it will be hidden by default]

</pre></details>

### Code of Conduct

- [X] I agree to follow Morpheus' Code of Conduct
- [X] I have searched the [open bugs](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by mdemoret-nv** [comment]
Ok, looks like its working now. Not sure what the issue was. Closing.
