### ISSUE TITLE
[BUG]: Source stage continues to yield on pipeline exception

### ISSUE THREAD

**Issue by efajardo-nv** [nv-morpheus/Morpheus#1525]
### Version

23.11

### Which installation method(s) does this occur on?

Conda

### Describe the bug.

During our pipeline testing, I observed that if one of the intermediate stages encounters an exception, the source generator stage continues running until all data batches are generated. I have implemented a `stop()` method that sets a switch to True, and this switch is checked in the while loop of the data yielding function. Ideally, I expected that if any of the stages encountered an error, the `stop` method of the source stage would be called, but it appears this is not happening.

### Minimum reproducible example

```python
import logging

from morpheus.config import Config
from morpheus.pipeline import LinearPipeline
from morpheus.pipeline.stage_decorator import source, stage
from morpheus.utils.logger import configure_logging

logger = logging.getLogger("morpheus.{__name__}")


@source
def source_stage() -> int:
    for i in range(5):
        logger.debug("Yield %s", i)
        yield i


@stage
def error_stage(message: int) -> int:
    logger.debug("Received %s", message)
    if message == 1:
        raise RuntimeError
    return message


def run_pipeline():
    configure_logging(log_level=logging.DEBUG)

    config = Config()

    pipeline = LinearPipeline(config)
    pipeline.set_source(source_stage(config))
    pipeline.add_stage(error_stage(config))

    pipeline.run()


if __name__ == "__main__":
    run_pipeline()
```

### Relevant log output

```
Yield 0
Yield 1
Yield 2
Yield 3
Yield 4
Received 0
Received 1
Exception occurred in pipeline. Rethrowing
Traceback (most recent call last):
  File "/opt2/gitrepos/efajardo-nv/Morpheus/morpheus/pipeline/pipeline.py", line 411, in post_start
    await executor.join_async()
  File "/opt2/gitrepos/efajardo-nv/Morpheus/pipeline_exception_test.py", line 22, in error_stage
    raise RuntimeError
RuntimeError
```

### Code of Conduct

- [X] I agree to follow Morpheus' Code of Conduct
- [X] I have searched the [open bugs](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by efajardo-nv** [comment]
#1838

**Comment by mdemoret-nv** [comment]
Closing in favor of #1838
