### ISSUE TITLE
[FEA]: Upgrade to RAPIDS 24.04/CUDA 12.4

### ISSUE THREAD

**Issue by pdmack** [nv-morpheus/Morpheus#1545]
### Is this a new feature, an improvement, or a change to existing functionality?

Change

### How would you describe the priority of this feature request

High

### Please provide a clear description of problem this feature solves

RAPIDS has begun generating matrixed builds of 24.04 for CUDA 12.4. We should align our builds to that when the time is appropriate. 

### Describe your ideal solution

Changes as needed to the versions of cuDF and RMM
CI checks
smoke tests (including container image builds)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the [open feature requests](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22%2Cimprovement%2Cenhancement) and have found no duplicates for this feature request

**Comment by mdemoret-nv** [comment]
Superceded by #1717
