### ISSUE TITLE
[BUG] from-file subcommand missing for pipeline-ae

### ISSUE THREAD

**Issue by dagardner-nv** [nv-morpheus/Morpheus#169]
**Describe the bug**
```
Usage: morpheus run pipeline-ae [OPTIONS] COMMAND1 [ARGS]... [COMMAND2
[ARGS]...]...
Try 'morpheus run pipeline-ae --help' for help.
Error: No such command 'from-file'.
```

Probably just an oversight or a copy/paste error

**Steps/Code to reproduce bug**
Attempt to build a pipeline-ae pipe using from-file on the cli

**Expected behavior**
working

**Comment by dagardner-nv** [comment]
The lack of a from-file sub-command for this pipeline is intentional as the rest of the stages in this pipeline expect messages of type `UserMessageMeta`. 

The from-cloudtrail source should be used instead.

**Comment by jwan2** [comment]
Is it possible to have 'from-kafka' option for pipeline-ae in the future?

**Comment by dagardner-nv** [comment]
I think we would be open to that if your wanted to open up a feature request for that.
