### ISSUE TITLE
Unnecessary input parameter used

### ISSUE THREAD

**Issue by ylnhari** [nv-morpheus/Morpheus#1693]
https://github.com/nv-morpheus/Morpheus/blob/c88527bee55a4e6b634e9a553d4a581a128e05a5/examples/digital_fingerprinting/production/morpheus/dfp/modules/dfp_inference.py#L100C28-L100C39

What is the purpose of including the 'client' parameter while calling this method when it doesn't appear to be utilized within the method's implementation?

**Comment by efajardo-nv** [comment]
Thanks @ylnhari. You are correct. The `client` parameter is not used. We'll remove it from both the module and stage implementation.
