### ISSUE TITLE
The `cache_mode` description in DFP docs is incorrect

### ISSUE THREAD

**Issue by ylnhari** [nv-morpheus/Morpheus#1696]
https://github.com/nv-morpheus/Morpheus/blob/26c95e13fe996dfed61f53dabf8f4267f8d84504/examples/digital_fingerprinting/production/morpheus/dfp/modules/dfp_rolling_window.py#L51

This comment seems to confuse the actual use of the config setting.

**Comment by efajardo-nv** [comment]
Thanks @ylnhari. Yes, that needs to be fixed.

**Comment by efajardo-nv** [comment]
Use the corrected descriptions in #1634 if `cache_mode` support is being added to stage implementation of DFP Rolling Window.
