### ISSUE TITLE
[EPIC] Morpheus Compartmentalization

### ISSUE THREAD

**Issue by mdemoret-nv** [nv-morpheus/Morpheus#1845]
Tracking issue for the Morpheus compartmentalization effort.

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

**Comment by AnuradhaKaruppiah** [comment]
Addressed in 24.10 - https://github.com/nv-morpheus/Morpheus/blob/branch-24.10/docs/source/conda_packages.md
