### ISSUE TITLE
[BUG]: Conda installs a redundant CPU build of torch

### ISSUE THREAD

**Issue by dagardner-nv** [nv-morpheus/Morpheus#1943]
### Version

24.10

### Which installation method(s) does this occur on?

Source

### Describe the bug.

We install torch via `pip` which is how we get the `2.4.0+cu124` version. 
I believe the `sentence-transformers` package is pulling in `torchvision` which in turn pulls in `libtorch`.

```
$ conda list | grep torch
libtorch                  2.4.0           cpu_generic_h4a3044c_1    conda-forge
torch                     2.4.0+cu124              pypi_0    pypi
torchdata                 0.8.0                    pypi_0    pypi
torchvision               0.19.1          cpu_py310hd9679db_0    conda-forge
```

### Minimum reproducible example

CONDA_ALWAYS_YES=true conda env create --solver=libmamba -n morpheus -y --file conda/environments/all_cuda-125_arch-x86_64.yaml

### Relevant log output

<details><summary>Click here to see error details</summary><pre>

 [Paste the error here, it will be hidden by default]

</pre></details>

### Full env printout

<details><summary>Click here to see environment details</summary><pre>

 [Paste the results of print_env.sh here, it will be hidden by default]

</pre></details>

### Code of Conduct

- [x] I agree to follow Morpheus' Code of Conduct
- [x] I have searched the [open bugs](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by efajardo-nv** [comment]
@dagardner-nv The `sentence-transformers` conda install in the release container results in the following pytorch packages in the container:
```
# packages in environment at /opt/conda/envs/morpheus:
#
# Name                    Version                   Build  Channel
libtorch                  2.4.1           cpu_generic_hb3b73e9_0    conda-forge
pytorch                   2.4.1           cpu_generic_py310hcbfaffa_0    conda-forge
torch                     2.4.0+cu124              pypi_0    pypi
torchvision               0.19.1          cpu_py310h0339c84_1    conda-forge
```
The VDB embedding stage then chooses to use CPU version. Replacing with `pip` package switches it back to GPU but it's not quite as fast (~3 min vs ~2 min in our example).
