### ISSUE TITLE
[DOC]: Add documentation page describing the compartmentalization change

### ISSUE THREAD

**Issue by mdemoret-nv** [nv-morpheus/Morpheus#1960]
### How would you describe the priority of this documentation request

High

### Describe the future/missing documentation

Add a new documentation page dedicated to the compartmentalization changes. This page should include:

- [ ] Information about the changes
- [ ] When did the change happen (because this page will be around for a while)
- [ ] Why did we make the change? Benefits?
- [ ] Isolation strategy moving forward.
- [ ] Where you can find the new conda packages

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
- [x] I have searched the [open documentation issues](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Adoc) and have found no duplicates for this bug report

**Comment by AnuradhaKaruppiah** [comment]
conda_packages.md has been added.
