### ISSUE TITLE
[BUG]: CI needs to trigger from main branch

### ISSUE THREAD

**Issue by dagardner-nv** [nv-morpheus/Morpheus#2042]
### Version

24.10

### Describe the bug.

This is needed to ensure that releases trigger a conda build

### Relevant log output

<details><summary>Click here to see error details</summary><pre>

 [Paste the error here, it will be hidden by default]

</pre></details>

### Full env printout

<details><summary>Click here to see environment details</summary><pre>

 [Paste the results of print_env.sh here, it will be hidden by default]

</pre></details>

### Code of Conduct

- [x] I agree to follow Morpheus' Code of Conduct
- [x] I have searched the [open bugs](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by cwharris** [comment]
For context: https://github.com/rapidsai/build-planning/issues/63

**Comment by dagardner-nv** [comment]
> For context: https://github.com/rapidsai/build-planning/issues/63
Redesigning our branching and release procedures is really outside the scope of this issue. In the short term, this issue is really a "Make it work like MRC" issue.
