### ISSUE TITLE
[FEA] Digital Fingerprinting Updates: Thresholding

### ISSUE THREAD

**Issue by jarmak-nv** [nv-morpheus/Morpheus#209]

**Comment by jarmak-nv** [comment]
@gbatmaz  - Please add a general high-level description here, thanks!

**Comment by gbatmaz** [comment]
Description:
Going forward, we will calculate a baseline reconstruction loss using the benign data and save the mean & std. Then, we will calculate a custom z-score metric using those two reference values every time a reconstruction loss is received. 
Code shared with @efajardo-nv , implementation in progress.
