### ISSUE TITLE
[FEA] Digital Fingerprinting Updates: Explainability

### ISSUE THREAD

**Issue by jarmak-nv** [nv-morpheus/Morpheus#210]
Top 3* contributing fields

**Comment by jarmak-nv** [comment]
@gbatmaz  - Please add a general high-level description here, thanks!

**Comment by gbatmaz** [comment]
Description:
-Along with the anomaly score, we will return the features that contribute to the loss most. (For each data type) 
-We may also return supporting information, e.g. if those features already had high variation in the benign set etc. 
I shared the code for the first part with @efajardo-nv  . The second part is still pending on me.

**Comment by gbatmaz** [comment]
I think we are ok for the next release right? @efajardo-nv 
We are still discussing the longer term features
