### ISSUE TITLE
[FEA] Masking for MultiMessage Type

### ISSUE THREAD

**Issue by jarmak-nv** [nv-morpheus/Morpheus#217]
This would allow for several non-adjacent rows to be included in a single `MultiMessage` instance.

Currently `MultiMessage` only supports an offset+count, so in the worst case scenario of filtering (#83) a single message containing 1024 rows coming into the filter stage could result in up to 512 messages being emitted.

Masking would allow for only a single message to be emitted.

**Comment by dagardner-nv** [comment]
I started looking into this a bit, just wanted to jot down my thoughts before I move on to something else. 

The MultiResponseProbsMessage messages contain both the original dataframe (`meta`) along with a cupy probabilities array (`probs`).

For the filter stage we use the probs array to determine which rows in the dataframe to include in the output. 

I think the idea here was to use numpy's Masked arrays for this (https://numpy.org/doc/stable/reference/maskedarray.html). However cupy doesn't appear to support this https://github.com/cupy/cupy/issues/2225. 

We could instead maintain a third `mask` array which would simply be the `detections` array:
`detections = (x.probs > self._threshold).any(axis=1)`

Alternately we could look into using cudf's `mask` or `query` methods

**Comment by dagardner-nv** [comment]
I see now, this is what we want to do:
```
detections = (x.probs > self._threshold).any(axis=1)
x.meta.loc[detections, :]
```

**Comment by dagardner-nv** [comment]
@jarmak-nv done
