### ISSUE TITLE
[FEA] EXPERIMENTAL Graph-Based Fraud Detection Workflow

### ISSUE THREAD

**Issue by jarmak-nv** [nv-morpheus/Morpheus#218]
Description
-----
This will remove the stellar graph dependency and move to the DGL framework. Add authentication graph workflow that takes a similar graph structure to the pipeline to the Morpheus experimental repo

(copied from comment below)

**Comment by jarmak-nv** [comment]
@tzemicheal  - Please add a general high-level description here, thanks!

**Comment by tzemicheal** [comment]
Description:
We will remove the stellar graph dependency and move to the DGL framework.  Add authentication graph workflow that takes a similar graph structure to the pipeline.
