### ISSUE TITLE
[BUG] log parsing example failure 

### ISSUE THREAD

**Issue by pdmack** [nv-morpheus/Morpheus#267]
**Describe the bug**
log parsing example fails in 22.06

```
Preprocessing rate: 0messages [00:00, ?messages/s] /opt/conda/envs/morpheus/lib/python3.8/site-packages/cudf/core/subword_tokenizer.py:189: UserWarning: When truncation is not True, the behavior currently differs from HuggingFace as cudf always returns overflowing tokens
  warnings.warn(warning_msg)es [00:00, ?messages/s]
Preprocessing rate[Complete]: 4960messages [Error hit!5.77messages/s]
TypeError: Implicit conversion to a NumPy array is not allowed. Please use `.get()` to construct a NumPy array explicitly.
Postprocessing rate: 0messages [00:04, ?messages/s]
At:
  cupy/_core/core.pyx(1397): cupy._core.core.ndarray.__array__
  /opt/conda/envs/morpheus/lib/python3.8/site-packages/pandas/core/frame.py(708): __init__
  /workspace/examples/log_parsing/postprocessing.py(61): _postprocess

WARNING: Logging before InitGoogleLogging() is written to STDERR
E20220708 15:41:41.967535 1414631 context.cpp:125] main/logparsing-postproc-7; rank: 0; size: 1; tid: 139862086588160: set_exception issued; issuing kill to current runnable. Exception msg: TypeError: Implicit conversion to a NumPy array is not allowed. Please use `.get()` to construct a NumPy array explicitly.

At:
  cupy/_core/core.pyx(1397): cupy._core.core.ndarray.__array__
  /opt/conda/envs/morpheus/lib/python3.8/site-packages/pandas/core/frame.py(708): __init__
  /workspace/examples/log_parsing/postprocessing.py(61): _postprocess
Preprocessing rate[Complete]: 4960messages [00:01, 1065.77messages/s]
E20220708 15:41:45.216320 1414454 runner.cpp:190] RunnE20220708 15:41:45.216850 1414454 instance.cpp:259] segment::Instance - an exception was caught while awaiting on one or more nodes - rethrowing 1024inf [00:07, 227.63inf/s]ages/s]
E20220708 15:41:45.216878 1414454 instance.cpp:218] pipeline::Instance - an exception was caught while awaiting on segments - rethrowing
Preprocessing rate[Complete]: 4960messages [00:01, 4229.90messages/s]
Inference rate[Complete]: 1024inf [00:04, 227.63inf/s]
Postprocessing rate[Complete]: 0messages [00:00, ?messages/s]
```

**Steps/Code to reproduce bug**
```
python ./examples/log_parsing/run.py     \
--num_threads 1    \
 --input_file ./models/datasets/validation-data/log-parsing-validation-data-input.csv     \
--output_file ./log-parsing-output.jsonlines     \
--model_vocab_hash_file=./models/training-tuning-scripts/sid-models/resources/bert-base-cased-hash.txt     \
--model_vocab_file=./models/training-tuning-scripts/sid-models/resources/bert-base-cased-vocab.txt     \
--model_seq_length=256     \
--model_name log-parsing-onnx     \
--model_config_file=./models/log-parsing-models/log-parsing-config-20220418.json     \
--server_url ai-engine:8001
```

**Expected behavior**
Example pipeline runs to completion.

**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal, Docker]
 - Method of Morpheus install: [Docker/k8s]

**Environment details**
https://gist.github.com/pdmack/177baf49e0f0265ad381298f7fa8e0c7

**Additional context**

**Comment by BartleyR** [comment]
@mdemoret-nv This is blocking one of our partners. Let's prioritize.

**Comment by efajardo-nv** [comment]
@pdmack noticed the versions in environment details are different in [cuda11.5_dev.yml](https://github.com/nv-morpheus/Morpheus/blob/branch-22.06/docker/conda/environments/cuda11.5_dev.yml). 

cupy                      10.6.0 (bug environment)
cupy                      9.5.0  (my dev container)

cudatoolkit               11.7.0 (bug environment)
cudatoolkit               11.5.1 (my dev container)

The example works for me even after I update cupy to 10.6. 

We should still do explicit conversion using `.get()` so I'll create a PR for that.

**Comment by efajardo-nv** [comment]
@mdemoret-nv found that the wrong pandas version (1.4.3) is being pip installed while conda/pip still reports that it's v.1.3.5. i'll investigate this further to find why this is happening.

**Comment by mdemoret-nv** [comment]
Here is the code snippet to determine that:

```bash
$ ./docker/run_container_release.sh 
Setting up ssh-agent auth socket
Launching nvcr.io/nvidia/morpheus/morpheus:v22.06.00a-runtime...
(morpheus) root@123456:/workspace# conda list | grep pandas
pandas                    1.3.5                    pypi_0    pypi
pandas-profiling          3.2.0              pyhd8ed1ab_0    conda-forge
(morpheus) root@123456:/workspace# python
iPython 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas
>>> pandas.__version__
'1.4.3'
```

**Comment by efajardo-nv** [comment]
1. changing order of `mamba env update cuda11.5_runtime.yml` and `mamba install morpheus` in dockerfile, i get pypi pandas 1.3.5 and verified that with pandas.__version. log parsing works.
2. remove mamba env update  --> conda-forge 1.4..3,  remove mamba install --> pypi 1.3.5
3. adding mamba install -c conda-forge pandas=1.3 before two commands --> conda-forge 1.3.5, log parsing works
4. adding pandas=1.3 to cuda11.5_runtime.yml --> conda-forge 1.3.5, log parsing works

discussed these results with @mdemoret-nv and will go with option 1 as quick fix but will continue investigating why we get pip version of pandas.

**Comment by pdmack** [comment]
For the temporary workaround, `mamba install -c conda-forge pandas=1.3` seems fine. Obviously that would need to be done each time inside the pod/container if it gets restarted.
