### ISSUE TITLE
[DOC] ransomware_detection readme updates

### ISSUE THREAD

**Issue by pdmack** [nv-morpheus/Morpheus#293]
## Report incorrect documentation

**Location of incorrect documentation**
examples/ransomware_detection/README.md

**Describe the problems or issues found in the documentation**
Just some updates. 

- Once #291 is addressed it makes sense to change the triton version to 22.06-py3
- `conda install dask==2022.5.2 distributed==2022.5.2`
   distributed is actually installed by the meta recipe (at least in the container image) at version 22.7

**Steps taken to verify documentation is incorrect**
List any steps you have taken:

- run the example

**Suggested fix for documentation**
Detail proposed changes to fix the documentation if you have any.

**Comment by bsuryadevara** [comment]
@pdmack dev container image doesn't have these dependencies. I'm gonna put a note in the `README.md` as shown below.

```
Make sure dask and distributed are installed in your conda environment before running the ransomware detection pipeline. Run the installation command specified below if not.

conda install dask==2022.7.0 distributed==2022.7.0
```
