### ISSUE TITLE
[DOC] Add a readme for the example section

### ISSUE THREAD

**Issue by jarmak-nv** [nv-morpheus/Morpheus#303]
**Report needed documentation**
Having a general overview of how these examples work/how to use will help prevent downstream questions/issues.

**Describe the documentation you'd like**
I'd like an introductory readme that covers usage/quirks for each example.

**Comment by mdemoret-nv** [comment]
To add to this, it should explain that examples with a `run.py` should be run from the example directory. Ones that just have a `README.md`, should be run from the morpheus repo root.
