### ISSUE TITLE
[FEA] Digital Fingerprinting Visualization

### ISSUE THREAD

**Issue by jarmak-nv** [nv-morpheus/Morpheus#321]
Build a DFP post-processing stage that converts DFP output to necessary inputs for DFP visualization UI. This stage must:
- Output overall anomaly score (`mean_abs_z`) and `z_loss` scores for each feature.
- Save output to multiple files by grouping results by a specified time period.

Work with Viz team to integrate pipeline with their UI.

**Comment by Nihel01** [comment]
Hi Morpheus team!, I saw the visualization presented at GTC, is this something that is already up somewhere in the repo?

**Comment by hamreni** [comment]
Hi, like Nihel01, I don't find the new fingerprinting dashboard visualization example, presented on GTC. I really like those charts and hope that you can provide some source for using and developing further!

**Comment by efajardo-nv** [comment]
@Nihel01 @hamreni We're polishing up the viz now. It will be included in the next release (22.11).
