### ISSUE TITLE
[FEA] Unify Stages Between Starter and Production DFP Workflow Examples

### ISSUE THREAD

**Issue by mdemoret-nv** [nv-morpheus/Morpheus#343]
**Is your feature request related to a problem? Please describe.**
There are currently 2 different implementations of the DFP Workflow: Starter and Production. These two implementations should use the same code if possible for input/output, preprocessing and post processing.

**Describe the solution you'd like**
The final solution should utilize as many of the same stages as possible for these two workflows to simplify development, fix bugs, and reuse as much code as possible.

Specifically, the preprocessing in the Starter example needs to be updated to use the new `DataFrameInputSchema` class

**Comment by mdemoret-nv** [comment]
Punting on this until 22.11

**Comment by bsuryadevara** [comment]
The DPF pipeline stages are listed below.

Production DFP Pipeline
```
MultiFileSource
DFPFileBatcherStage
DFPFileToDataFrameStage
MonitorStage
DFPSplitUsersStage
DFPRollingWindowStage
DFPPreprocessingStage
DFPTraining
DFPMLFlowModelWriterStage
DFPInferenceStage
DFPPostprocessingStage
WriteToFileStage

```

Starter DFP Pipeline
```
CloudTrailSourceStage
TrainAEStage
PreprocessAEStage
AutoEncoderInferenceStage
AddScoresStage
SerializeStage
WriteToFileStage
```

**Comment by jarmak-nv** [comment]
Putting all eng resources into the prod workflow, starter will stay as is.
