### ISSUE TITLE
[DOC] Complete Documentation for the Starter DFP Workflow Example

### ISSUE THREAD

**Issue by mdemoret-nv** [nv-morpheus/Morpheus#344]
## Report needed documentation

**Report needed documentation**
The Starter DFP Workflow example needs to be documented to make it easy for users to get started.

**Describe the documentation you'd like**
The documentation should include:

- [ ] A statement of the problem that is solved with this workflow
   - [ ] Including an example of the input data
- [x] How the Starter DFP example differs from the Production
- [x] How to run the example
- [ ] Where to extend this example for different input datasets

**Comment by jarmak-nv** [comment]
@efajardo-nv does https://github.com/nv-morpheus/Morpheus/pull/370 close all of this, or part of it?

**Comment by efajardo-nv** [comment]
@jarmak-nv there is also starter dfp documentation in the [README] (https://github.com/nv-morpheus/Morpheus/blob/branch-22.09/examples/digital_fingerprinting/starter/README.md) which was added as part of PR #315.

**Comment by jarmak-nv** [comment]
Closing - will spawn some new doc issues for starter pipeline as we align with production pipeline.
