### ISSUE TITLE
[FEA] Publish the Duo and Azure Test Data for DFP to S3

### ISSUE THREAD

**Issue by mdemoret-nv** [nv-morpheus/Morpheus#346]
**Is your feature request related to a problem? Please describe.**
To properly test the DFP production pipeline which uses S3 to download the data from a source, we need to publish the test dataset to S3.

**Describe the solution you'd like**
Both the Duo and Azure test data should be published to a publicly available S3 bucket.

**Comment by mdemoret-nv** [comment]
Waiting on Ops to upload the data

**Comment by BartleyR** [comment]
This is completed
