### ISSUE TITLE
[DOC]: Dataset Documentation Inside the Data Folder

### ISSUE THREAD

**Issue by BartleyR** [nv-morpheus/Morpheus#431]
### How would you describe the priority of this documentation request

High

### Describe the future/missing documentation

Although we have documentation about datasets used for model training, testing, and validation as part of the model cards, it would be useful to have this information easily accessible as part of the `data` folder (https://github.com/nv-morpheus/Morpheus/tree/branch-22.11/examples/data). It is difficult to determine where data is coming from if you don't know to go look at the individual model cards.

### Where have you looked?

The information is available in the model cards (https://github.com/nv-morpheus/Morpheus/tree/branch-22.11/models), but it should be replicated as part of the `data` folder.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the [open documentation issues](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Adoc) and have found no duplicates for this bug report

**Comment by jarmak-nv** [comment]
To prevent us from needing to duplicate the info (and maintain two locations as things change), would it suffice to have a clean readme pointing users to the right place? Something like below.

---

## About
This folder contains the datasets used for model training - to learn more about each dataset please check the readme(link) in the model cards folder.

- [Ransomware](https://github.com/nv-morpheus/Morpheus/tree/branch-22.11/models#ransomware-detection-via-appshield)
- etc

---

Happy to get a quick PR in to cover this if that's a good solution.
