### ISSUE TITLE
[FEA]: Create unittests for DFP example

### ISSUE THREAD

**Issue by dagardner-nv** [nv-morpheus/Morpheus#472]
### Is this a new feature, an improvement, or a change to existing functionality?

Improvement

### How would you describe the priority of this feature request

Medium

### Please provide a clear description of problem this feature solves

The DFP example contains a sizable code base with multiple custom stages.
In order to ensure that the DFP example doesn't break we should creates some tests for it, and run it as a part of our CI system.

### Describe your ideal solution

Write more tests.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the [open feature requests](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22%2Cimprovement%2Cenhancement) and have found no duplicates for this feature request

**Comment by mdemoret-nv** [comment]
Closing since tests were added for DFP in #940
