### ISSUE TITLE
[DOC]: Customize/Extend AutoEncoder Model

### ISSUE THREAD

**Issue by bsuryadevara** [nv-morpheus/Morpheus#500]
### How would you describe the priority of this documentation request

Medium

### Describe the future/missing documentation

One of the teams tried to adapt existing autoencoder model in Morpheus to their own approach (faced many issues, wasn’t clear how to proceed, got many errors)

Provide documentation to customize/extend autoencoder model.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the [open documentation issues](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Adoc) and have found no duplicates for this bug report

**Comment by mdemoret-nv** [comment]
AutoEncoder has been forked into the repo
