### ISSUE TITLE
[BUG]: Unable to Retrain the Models

### ISSUE THREAD

**Issue by bsuryadevara** [nv-morpheus/Morpheus#504]
### Version

22.09

### Which installation method(s) does this occur on?

Docker

### Describe the bug.

Most of the model (except one) can’t be retrained

### Code of Conduct

- [X] I agree to follow Morpheus' Code of Conduct
- [X] I have searched the [open bugs](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by mdemoret-nv** [comment]
@bsuryadevara Can you provide more information? Is this still an issue?

**Comment by bsuryadevara** [comment]
Not an issue anymore. Closing the issue.
