### ISSUE TITLE
[DOC]: CLX/Morpheus Parity Comparison - Data Science

### ISSUE THREAD

**Issue by BartleyR** [nv-morpheus/Morpheus#509]
### How would you describe the priority of this documentation request

Medium

### Describe the future/missing documentation

The current RAPIDS CLX library has notebook examples that could be integrated into Morpheus experimental. As the first step towards this, we wish to understand the parity between the example notebooks in CLX and those available in Morpheus and Morpheus experimental in terms of the use cases (workflows), dependencies (internal and external), models, capabilities, and illustrative properties.

### Where have you looked?

No such documentation exist in CLX or Morpheus

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the [open documentation issues](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Adoc) and have found no duplicates for this bug report

**Comment by raykallen** [comment]
completed
