### ISSUE TITLE
[DOC] gnn_fraud_detection_pipeline needs updating

### ISSUE THREAD

**Issue by dagardner-nv** [nv-morpheus/Morpheus#54]
## Report incorrect documentation
Minimally psutil needs to be replaced

**Location of incorrect documentation**
`examples/gnn_fraud_detection_pipeline`

**Comment by dagardner-nv** [comment]
Looks like @cwharris  is already working on this

**Comment by mdemoret-nv** [comment]
@dagardner-nv Is this resolved or is it still outstanding?

**Comment by dagardner-nv** [comment]
Still an issue.

**Comment by mdemoret-nv** [comment]
Closing this with the fixes in PR #182
