### ISSUE TITLE
[DOC]: Proof read docs/source/index.rst

### ISSUE THREAD

**Issue by dagardner-nv** [nv-morpheus/Morpheus#541]
### How would you describe the priority of this documentation request

Medium

### Please provide a link or source to the relevant docs

docs/source/index.rst

### Describe the problems in the documentation

Please proof read the `docs/source/index.rst` in the https://github.com/dagardner-nv/Morpheus/tree/david-docs-23.01-restructure branch and run spell check on the rendered text.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the [open documentation issues](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Adoc) and have found no duplicates for this bug report

**Comment by efajardo-nv** [comment]
LGTM. I was able to build docs. Everything rendered fine. Proofread and spell checked. All links worked. Only thing I noticed was search link on bottom took you to a page that didn't offer any way to search. Assume that's still WIP.

**Comment by dagardner-nv** [comment]
That's a good catch, I noticed that the search box on the left does work, and directs to `search.html`, however the search link at the bottom goes to the same page but as you pointed out it doesn't display a search box.
