### ISSUE TITLE
[FEA]: Publish a Morpheus models container

### ISSUE THREAD

**Issue by dagardner-nv** [nv-morpheus/Morpheus#552]
### Is this a new feature, an improvement, or a change to existing functionality?

Improvement

### How would you describe the priority of this feature request

Low (would be nice)

### Please provide a clear description of problem this feature solves

We advertise in our documentation that this is the easiest way to start using Morpheus and the pre-trained modules is to use one of our pre-built Docker containers on NGC. However this introduces a few difficulties :

1. Our containers are large because they include the models
2. The models are inside the container, requiring the user to launch triton from inside the container, which means they need to mount the docker socket file
3. The docker command isn't in the container requiring the user to run the `docker/install_docker.sh` script

### Describe your ideal solution

Publish a separate models container that layers on top of Triton

### Describe any alternatives you have considered

Install docker in the default container image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the [open feature requests](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22%2Cimprovement%2Cenhancement) and have found no duplicates for this feature request

**Comment by pdmack** [comment]
```
The models are inside the container, requiring the user to launch triton from inside the container, which means they need to mount the docker socket file
The docker command isn't in the container requiring the user to run the docker/install_docker.sh script
```

The k8s instructions have the user copy out the models, configs, datasets to a host path that can be shared amongst the containers.

**Comment by dagardner-nv** [comment]
@pdmack does that require access to the `kubectl` command, and thus require running in K8? Is there an equivalent for users running docker locally?

**Comment by pdmack** [comment]
A user could also use the `docker cp ...` command to move the models out of the container to a host path.

**Comment by dagardner-nv** [comment]
That would be a viable alternative then.

**Comment by dagardner-nv** [comment]
Part of this would be to revert and adjust the changes in #1507
