### ISSUE TITLE
[BUG]: Replace base docker image gpuci/miniforge-cuda

### ISSUE THREAD

**Issue by dagardner-nv** [nv-morpheus/Morpheus#616]
### Version

23.01

### Which installation method(s) does this occur on?

Docker

### Describe the bug.

`gpuci/miniforge-cuda` will be deprecated in the near future.
`rapidsai/mambaforge-cuda` should be a suitable replacement.

ref:
https://hub.docker.com/r/rapidsai/mambaforge-cuda/
https://github.com/rapidsai/mambaforge-cuda

related MRC issue https://github.com/nv-morpheus/MRC/issues/266

### Minimum reproducible example

```shell
n/a
```

### Code of Conduct

- [X] I agree to follow Morpheus' Code of Conduct
- [X] I have searched the [open bugs](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by cwharris** [comment]
`rapidsai/mambaforge-cuda` contains more than we need to build and run morpheus. We should use a slimmer container, such as  `nvidia/cuda`. I've tested this with the DOCA GPUNetIO changes. Some installs needed to be updated, but we can reference my branch to see what those are. https://github.com/cwharris/Morpheus/blob/doca-integration-refresh/docker/Dockerfile

**Comment by dagardner-nv** [comment]
We currently use this as the base for both the main image and for our mlflow image `models/mlflow/docker/Dockerfile`

**Comment by dagardner-nv** [comment]
Looking at `rapidsai/mambaforge-cuda:cuda11.5.1-base-ubuntu20.04-py3.8`
