### ISSUE TITLE
[FEA]: Make graphviz rankdir configurable

### ISSUE THREAD

**Issue by nvawood** [nv-morpheus/Morpheus#643]
### Is this a new feature, an improvement, or a change to existing functionality?

Change

### How would you describe the priority of this feature request

Low (would be nice)

### Please provide a clear description of problem this feature solves

I want Morpheus to support changing the direction of Graphviz pipeline images, because I find longer pipelines difficult to visualize in a left-to-right format.

### Describe your ideal solution

A new command line parameter that sets the rankdir argument.
```python
@click.option('--viz_direction',
              default="LR",
              type=click.Choice(["LR", "TB", "BT", "RL"], case_sensitive=True),
              help="Set the direction for the Graphviz pipeline diagram.")

pipeline.visualize(kwargs["viz_file"], rankdir=viz_direction)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the [open feature requests](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22%2Cimprovement%2Cenhancement) and have found no duplicates for this feature request

**Comment by mdemoret-nv** [comment]
@nvawood `rankdir` can currently be configured if you use the `Pipeline.visualize("my_file.png", rankdir="TB")` method. Does this satisfy this request or do you need it part of the CLI?

**Comment by nvawood** [comment]
I think if it's going to remain an option in the CLI, then it should be configurable there as well.
