### ISSUE TITLE
[BUG]: DFP example dfp_duo_training.ipynb errors out with ModuleNotFoundError: No module named 'mrc'

### ISSUE THREAD

**Issue by Tzahi-cpacket** [nv-morpheus/Morpheus#660]
### Version

v23.01.00

### Which installation method(s) does this occur on?

Docker

### Describe the bug.

When trying to run dfp_duo_training.ipynb from dfp production example, got an error in the second cell (the "imports" cell). the error reads:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In [2], line 8
      5 from datetime import datetime
      6 from functools import partial
----> 8 from dfp.stages.dfp_file_batcher_stage import DFPFileBatcherStage
      9 from dfp.stages.dfp_file_to_df import DFPFileToDataFrameStage
     10 from dfp.stages.dfp_mlflow_model_writer import DFPMLFlowModelWriterStage

File /workspace/examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_file_batcher_stage.py:21
     18 from datetime import datetime
     20 import fsspec
---> 21 import mrc
     22 import pandas as pd
     23 from mrc.core import operators as ops

ModuleNotFoundError: No module named 'mrc'

### Minimum reproducible example

```shell
# in /morpheus
# from a machine that had v22.11.00 installed previously


$ git checkout -b mybranch v23.01.00
$ ./docker/build_container_release.sh
$ cd examples/digital_fingerprinting/production
$ docker-compose build
$ docker-compose up jupyter

run in jupyter dfp_duo_training.ipynb
in cell [2]
```

### Full env printout

```shell
In my installation (v23.01.00) the ./external/utilities folder is empty. no scripts
```

### Code of Conduct

- [X] I agree to follow Morpheus' Code of Conduct
- [X] I have searched the [open bugs](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by Tzahi-cpacket** [comment]
Hi,

Thanks for the quick reply,

trying the git submodule like so:

# in branch mybranch (which is unchanged local branch  v23.01.00)
# in directory  /morpheus/examples/digital_fingerprinting/production/ 
$ docker-compose down
# in directory /morpheus
$ git submodule update --init --recursive
$ ./docker/build_container_release.sh
$ cd examples/digital_fingerprinting/production
$ export MORPHEUS_CONTAINER_VERSION="$(git describe --tags --abbrev=0)-runtime"
$ docker-compose build
$ docker-compose up jupyter

I see the same error as before.

but,

I now have a morpheus/external/utilities/scripts folder with a print_env.sh,

the first few lines of that output are (will happily send the whole output if useful, its long):
<details><summary>Click here to see environment details</summary><pre>

     **git***
     commit 6e1d4e62e8ad36a3ff45652f4d1aa03810de3751 (HEAD, origin/branch-23.01)
     Author: Michael Demoret <mdemoret@nvidia.com>
     Date:   Mon Jan 30 18:40:20 2023 -0700

     Updating CHANGELOG
     **git submodules***


Also, from the jupyter lab environment, I opened a terminal
# bash
(morpheus) root@0ac900292a3f:/workspace/examples/digital_fingerprinting/production/morpheus# cd /
(morpheus) root@0ac900292a3f:/# find . |grep mrc
./usr/lib/node_modules/npm/man/man5/npmrc.5
./usr/lib/node_modules/npm/docs/output/configuring-npm/npmrc.html
./usr/lib/node_modules/npm/.npmrc
q./workspace/external/utilities/cmake/morpheus_utils/package_config/mrc
./workspace/external/utilities/cmake/morpheus_utils/package_config/mrc/Configure_mrc.cmake
./workspace/external/morpheus-visualizations/.npmrc

so no mrc there, but on the other hand:

(morpheus) root@0ac900292a3f:/# find . |grep srf
./opt/conda/envs/morpheus/lib/python3.8/site-packages/jedi/third_party/django-stubs/django-stubs/views/decorators/csrf.pyi
./opt/conda/envs/morpheus/lib/python3.8/site-packages/jedi/third_party/django-stubs/django-stubs/views/csrf.pyi
./opt/conda/envs/morpheus/lib/python3.8/site-packages/jedi/third_party/django-stubs/django-stubs/middleware/csrf.pyi
./opt/conda/envs/morpheus/lib/python3.8/site-packages/jedi/third_party/django-stubs/django-stubs/core/checks/security/csrf.pyi
./opt/conda/envs/morpheus/lib/python3.8/site-packages/srf-22.9.0.dist-info
./opt/conda/envs/morpheus/lib/python3.8/site-packages/srf-22.9.0.dist-info/direct_url.json
./opt/conda/envs/morpheus/lib/python3.8/site-packages/srf-22.9.0.dist-info/RECORD
...

So I got an image with srf libraries, not mrc libraries, but I don't know why is that. 

Thanks

**Comment by dagardner-nv** [comment]
I've run into this a few times, and I don't know of a good way to force docker-compose to rebuild the containers. What I do is:
```bash
docker compose stop
docker compose rm
docker container ls -a
docker container rm <all containers that look like dfp_morpheus_*>
docker image ls
docker image rm <all containers that looks like dfp_morpheus_* and the weird hash ones without a name>

export MORPHEUS_CONTAINER_VERSION="$(git describe --tags --abbrev=0)-runtime"
docker-compose build --no-cache
```

**Comment by jarmak-nv** [comment]
@Tzahi-cpacket closing this since it looks like you've resolved and David has provided steps in case it happens again. If anything else comes up, please reopen or file a new issue - thanks!
