### ISSUE TITLE
[FEA] Replicate current devcontainer functionality using features

### ISSUE THREAD

**Issue by mdemoret-nv** [nv-morpheus/Morpheus#702]
The current `.devcontainer` code could be improved by utilizing features where possible. A first pass should replicate the current functionality that we have with the dev container:

- [x] Setup the docker user to match the host user
- [x] Install Mamba with the correct user permissions
   - [x] Including setting the default conda environment
   - [x] The default conda environment should be activated as part of the image or entry point to allow VS Code to use conda installed packages
   - [x] The conda environment should be mounted from the host to persist between sessions
- [x] Setup docker-in-docker
- [x] Add the Github CLI
   - [ ] Including mounting the host configuration into the container where possible
- [x] Setup the GDB Pretty printer for use with conda environments

**Comment by cwharris** [comment]
we'll want to use docker-from-docker so we can set up a network visible from within and outside the container. docker-from-docker also allows us to cache images, whereas docker-in-docker does not really.
