### ISSUE TITLE
[BUG]: compile.sh failing due to morpheus_utils/load

### ISSUE THREAD

**Issue by tanmoyio** [nv-morpheus/Morpheus#736]
### Version

23.01

### Which installation method(s) does this occur on?

Source

### Describe the bug.

I am trying to build morpheus from 23.01 release source. It seems like it couldn't include the `morpheus_utils/load` file.

### Minimum reproducible example

```shell
./scripts/compile.sh
```

### Relevant log output

```shell
+ set -e
+ BUILD_DIR=build
+ echo 'Runing CMake configure...'
Runing CMake configure...
+ cmake -B build -GNinja -DCMAKE_MESSAGE_CONTEXT_SHOW=ON -DMORPHEUS_USE_CLANG_TIDY=OFF -DMORPHEUS_PYTHON_INPLACE_BUILD=ON -DMORPHEUS_USE_CCACHE=ON -DMORPHEUS_USE_CONDA=ON '' .
CMake Warning:
  Ignoring empty string ("") provided on the command line.


CMake Error at CMakeLists.txt:75 (include):
  include could not find requested file:

    morpheus_utils/load


CMake Error at CMakeLists.txt:78 (morpheus_utils_initialize_package_manager):
  Unknown CMake command "morpheus_utils_initialize_package_manager".


-- Configuring incomplete, errors occurred!
```

### Code of Conduct

- [X] I agree to follow Morpheus' Code of Conduct
- [X] I have searched the [open bugs](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by pdmack** [comment]
I believe `git submodule update --init --recursive` in the morpheus root dir will fix this before running the compile script. Please let us know if that is not the case.
@dagardner-nv this was the docs blind spot I mentioned after the utils sub-module was introduced.

**Comment by dagardner-nv** [comment]
It looks like its in the docs for 23.03, but not 23.01
https://github.com/nv-morpheus/Morpheus/blob/branch-23.03/docs/source/developer_guide/contributing.md#clone-the-repository-and-pull-large-file-data-from-git-lfs

**Comment by tanmoyio** [comment]
thanks @pdmack @dagardner-nv,  the issue has been resolved
