### ISSUE TITLE
[FEA]: Add a `InMemorySinkStage` class to aid in testing

### ISSUE THREAD

**Issue by mdemoret-nv** [nv-morpheus/Morpheus#746]
### Is this a new feature, an improvement, or a change to existing functionality?

New Feature

### How would you describe the priority of this feature request

Medium

### Please provide a clear description of problem this feature solves

Many of our tests follow this pattern:
```python
    pipe.add_stage(
        WriteToFileStage(config, filename=out_file, overwrite=False, include_index_col=(output_type == "json")))
    pipe.run()

    assert_path_exists(out_file)

    validation_file = os.path.join(TEST_DIRS.tests_data_dir, "filter_probs.csv")
    input_data = np.loadtxt(validation_file, delimiter=",", skiprows=1)

    if output_type == "csv":
        # The output data will contain an additional id column that we will need to slice off
        output_data = np.loadtxt(out_file, delimiter=",", skiprows=1)
    else:  # assume json
        df = read_file_to_df(out_file, file_type=FileTypes.Auto)
        output_data = df.values

    # Somehow 0.7 ends up being 0.7000000000000001
    output_data = np.around(output_data, 2)
    assert output_data.tolist() == input_data.tolist()
```
Which does the following:

1. Writes the pipeline output to a file
2. Checks that the file exists
3. Reads the file
4. Then compares the data

This is slow, cumbersome and error prone for testing when all we need is the final dataframe loaded into memory.

### Describe your ideal solution

Instead, we should have a stage similar to the `ValidationStage` (Or it could be an improvement to the `ValidationStage`) which holds all messages sent to it in memory. Then once the pipeline is complete, the user could then access the concatenated dataframe. This would function exactly the same as the `WriteToFileStage` and reading the file, except with less steps.

There is already something similar [here](https://github.com/nv-morpheus/Morpheus/blob/branch-23.03/tests/test_nonlinear_pipeline.py#L79) and should be used as a starting point.

### Describe any alternatives you have considered

One alternative would be to make the `InMemorySinkStage` a base class for several other utility classes. For example, the hierarchy could be:

1. `InMemorySinkStage`
   1. Does nothing more than concat all messages into a single dataframe.
1. `CompareDataframeStage`
   1. Derives from `InMemorySinkStage` and performs `compare_df.compare_df()` saving the results to a member
1. `ValidationStage`
   1. Derives from `CompareDataframeStage` and writes the results calculated in `CompareDataframeStage` to a file like it currently does

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the [open feature requests](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22%2Cimprovement%2Cenhancement) and have found no duplicates for this feature request

**Comment by cwharris** [comment]
I like the idea of InMemorySinkStage, but I think having subclasses to this that execute test logic (`compare_df.compare_df()`) or writes them to a file after checking them is an antipattern. We probably want to keep the test code separate from the workflow/pipeline itself.

**Comment by dagardner-nv** [comment]
@cwharris I don't think its an anti-pattern, as they aren't performing any sort of test asserts, but would simply be performing a comparison of two dataframes and reporting the results. It would still be the test itself that would decide to pass or fail based on the acceptable threshold. 

Also the current `CompareDataframeStage` is in the `tests/` dir and thus not a part of the public API. Although this issue leaves it a bit open if `InMemorySinkStage` would be a part of the public API or if it would exist only inside the tests.
