### ISSUE TITLE
[FEA] Make the Morpheus CLI Extendable with the Ability to Add New Commands

### ISSUE THREAD

**Issue by mdemoret-nv** [nv-morpheus/Morpheus#85]
**Is your feature request related to a problem? Please describe.**
All pipelines that define at least 1 custom Stage must use the Python interface and cannot use the CLI. This is because there is no way to register new stages with the CLI unless they are built as first-party stages. This forces all of our built-in examples to use the python interface, duplicating a lot of click commands.

**Describe the solution you'd like**
Custom stages could be registered as commands with the CLI using various methods (such as a decorator). Once registered, CLI commands simply forward all options as `kwargs` to the constructor of each stage.

**Additional context**
Custom stages could be automatically discovered using the `entry_point` functionality in python. This is used by tools such as `pytest` to build extensions into the pytest CLI.

**Comment by lobotmcj** [comment]
[click-plugins](https://github.com/click-contrib/click-plugins) has not been updated in a few years but may be helpful as an example solution even if you don't use it directly.
