### ISSUE TITLE
Replace the classes and functions in `morpheus.utils.column_info` with equivalents from NVTabular

### ISSUE THREAD

**Issue by jarmak-nv** [nv-morpheus/Morpheus#863]
1. Map all implementations of `ColumnInfo` to NVTabular operation equivalents
      1. If any cannot be mapped, create custom operations
   2. Replace all uses of the `DataFrameInputSchema` class with `nvt.Schema`
      1. This could also use `nvt.Workflow` potentially
   3. Replace all uses of `process_dataframe` with `nvt.Workflow.fit_transform()`
   4. Add metadata tags for use in specific pipelines implementations (i.e. UserID column tags, date tags, etc.)
   5. Ideally, we would keep this as backwards compatible as possible keeping the existing class names and public API and replace the implementation with NVT

**Comment by drobison00** [comment]
(1) - All ColumnInfo objects have been directly mapped to nvt workflow equivalents; in a number of cases operators needed to be implemented with a new custom 'MutateOp', that allows for new DataFrame columns to be constructed and have their schema definitions forwarded.

(2) -  Its not clear that DataFrameInputSchema objects have a directly analogous nvt.Schema representation as DataFrameInputSchema objects define a composition of operators with an implicit ordering, and concepts like json_columns. Instead, existing DataFrameInputSchema objects can now be converted into an equivalent nvt.Workflow via `dataframe_input_schema_to_nvt_workflow`.

(3) - This is implemented; however, fit_transform returns an nvt.Dataset, not a DataFrame. NVT offers various ways of returning the underlying DataFrame from a dask data frame, cudf, or cpu (pandas) format. To handle this, process_dataframe now has additional configuration parameters.

(4) - This isn't entirely clear in terms of how we want things to be used or how columns should be tagged and can probably be left to an alternate PR.

(5) - Backwards compatibility is retained everywhere; process_dataframe is now able to take a `DataFrameInputSchema` or `nvt.Workflow` object.
