### ISSUE TITLE
NVTabular - Update DFEncoder data ingestion and ETL to use NVTabular

### ISSUE THREAD

**Issue by jarmak-nv** [nv-morpheus/Morpheus#867]
- [ ] Update `dfencoder.AutoEncoder.init_features()`
   - `init_features` takes a sample dataframe and determines the schema from the DataFrame's column types
   -  Columns are put into 1 of 3 buckets: categorical, numerical and binary
   - This should be replaced to use NVTabular's schema and improve on the number of column types available
   - The ability should be added to `dfencoder.AutoEncoder` to allow manual overriding of the DataFrame schema (i.e. Supply specific operations or an entire schema which would bypass `init_features` all together)
- [ ] Update `dfencoder.AutoEncoder.build_model()`
   - `build_model` takes the determined schema from a sample DataFrame and builds the auto encoder model from this schema
   - This requires mapping the schema to specific PyTorch functions before concatting everthing together for the core auto encoder layers.
   - We would need to update the current code to map from NVTabular schema instead of the current system
      - We should look at other models in Merlin for examples on how to do this
- [ ] Update `dfencoder.AutoEncoder.prepare_df()`
   - `prepare_df` takes an input DataFrame and runs it through the preprocesser to get the final input before passing it to PyTorch
   - This will need to be replaced with a `nvt.Workflow` that takes the schema determined from the `init_features` function
   - We should look at speeding this up with parallelization or sharding across GPUs if needed.

**Comment by mdemoret-nv** [comment]
Putting this on hold while we re-prioritize the updates to DFP
