### ISSUE TITLE
NVTabular - Add tests to DFEncoder

### ISSUE THREAD

**Issue by jarmak-nv** [nv-morpheus/Morpheus#869]
- [ ] Start with sample tests representative of the DFP type workloads (i.e. use DFP sample data) that run using the existing DFEncoder in the separate repo
- [ ] Run all those same tests using the new implementation, validating the output against the old code
- [ ] Add new tests for any additional features that were added above and beyond due to NVT

**Comment by mdemoret-nv** [comment]
As of 23.07, new tests have been added for DFP and NVTabular is now used for all ETL. Closing
