### ISSUE TITLE
NVTabular MultiGPU

### ISSUE THREAD

**Issue by jarmak-nv** [nv-morpheus/Morpheus#871]
## Overview
Once a baseline version of the DFEncoder model has been created and validated, we could make a new class `MultiGpuAutoEncoder`, which derives from `AutoEncoder` but runs the training loop assuming multiple GPUs are available.

```[tasklist]
- [ ] Create `MultiGpuAutoEncoder` deriving from `AutoEncoder`
- [ ] Override the base functions as necessary to perform the training across multiple GPUs
- [ ] Add multi GPU training tests (TBD on how this would be run in CI)
- [ ] Update documentation with examples on how to train using multi-GPU
```

### On overriding base functions:
- This may involve overriding one or more functions depending on how multi-GPU training works in PyTorch
- Additional functionality may need to be pulled out of the base training loop so it can be used by the derived class as well

**Comment by mdemoret-nv** [comment]
Completed with #938
