### ISSUE TITLE
[FEA]: DFP Stress/Benchmark testing Updates

### ISSUE THREAD

**Issue by raykallen** [nv-morpheus/Morpheus#890]
### Is this a new feature, an improvement, or a change to existing functionality?

New Feature

### How would you describe the priority of this feature request

High

### Please provide a clear description of problem this feature solves

I want to benchmark the DFP workflow with integrated training on different hardware with a real-world dataset size.

### Describe your ideal solution

An example script that can repeatably run a full example of the integrated training DFP workflow when provided data in S3 or local file.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the [open feature requests](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22%2Cimprovement%2Cenhancement) and have found no duplicates for this feature request

**Comment by bsuryadevara** [comment]
@raykallen just FYI. [Here](https://github.com/bsuryadevara/Morpheus/tree/890-fea-end-to-end-example-of-dfp-with-integrated-traning/examples/digital_fingerprinting/production/morpheus/benchmarks) is the progress on DFP benchmarks. I'm going to create a notebook for integrated training example
