### ISSUE TITLE
[BUG]: CI Not Checking Output of `yapf`

### ISSUE THREAD

**Issue by mdemoret-nv** [nv-morpheus/Morpheus#895]
### Version

23.07

### Which installation method(s) does this occur on?

Docker, Conda, Source

### Describe the bug.

When CI runs, only the output of `isort` and `flake8` are used to fail the check stage. Code is here: https://github.com/nv-morpheus/Morpheus/blob/276c2855403dbcf5711e3a68b03ecb30310131b7/ci/scripts/python_checks.sh#L104

### Minimum reproducible example

```shell
Run `ci/scripts/python_checks.sh` with formatting issues in a python file.
```

### Code of Conduct

- [X] I agree to follow Morpheus' Code of Conduct
- [X] I have searched the [open bugs](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by dagardner-nv** [comment]
This was fixed in PR #950
