### ISSUE TITLE
[DOC]: docker-compose fails, while 'docker compose' works to build DFP production

### ISSUE THREAD

**Issue by dagardner-nv** [nv-morpheus/Morpheus#919]
### How would you describe the priority of this documentation request

Medium

### Please provide a link or source to the relevant docs

https://github.com/nv-morpheus/Morpheus/blob/branch-23.07/examples/digital_fingerprinting/production/README.md

### Describe the problems in the documentation

In our docs we instruct users to use `docker-compose` rather than `docker compose`.

On my system I encountered this error:
```
$ docker-compose build
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.jupyter.deploy.resources.reservations value Additional properties are not allowed ('devices' was unexpected)
services.morpheus_pipeline.deploy.resources.reservations value Additional properties are not allowed ('devices' was unexpected)
Unsupported config option for services.jupyter: 'profiles'
Unsupported config option for services.morpheus_pipeline: 'profiles'
services.jupyter.build contains unsupported option: 'target'
services.morpheus_pipeline.build contains unsupported option: 'target'
```

This could just be a version mis-match on my system, and I was using the OS installed docker not the one in the conda env:
```
$ docker --version
Docker version 20.10.5+dfsg1, build 55c4c88
$ docker-compose --version
docker-compose version 1.25.0, build unknown
```

### (Optional) Propose a correction

1) Determine if we are doing anything in `examples/digital_fingerprinting/production/docker-compose.yml` requiring a minimum version of docker compose.

2) Document which commands the user should use depending on their version of docker

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the [open documentation issues](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Adoc) and have found no duplicates for this bug report

**Comment by jarmak-nv** [comment]
https://docs.docker.com/compose/reference/


> The new Compose V2, which supports the compose command as part of the Docker CLI, is now available.
> 
> Compose V2 integrates compose functions into the Docker platform, continuing to support most of the previous docker-compose features and flags. You can run Compose V2 by replacing the hyphen (-) with a space, using docker compose, instead of docker-compose.

https://www.docker.com/blog/announcing-compose-v2-general-availability/

> April 26, 2022 marks the GA of Docker Compose V2. Starting today, Compose V2 is the standard across all documentation, and Compose V2 will become the developer default on Docker Desktop. However, you can continue aliasing docker-compose to docker compose and opt-out of V2 via the Docker Desktop UI — or by entering the docker-compose disable-v2 command.

looks like v2 went GA 2 days ago, so maybe why this is just popping up now?
