### ISSUE TITLE
[DOC] Add NGC references back to README

### ISSUE THREAD

**Issue by BartleyR** [nv-morpheus/Morpheus#92]
**Report needed documentation**
We removed the NGC references from the getting started section temporarily as to avoid confusion on the multiple paths to get started. The removed link directed users here: [https://catalog.ngc.nvidia.com/orgs/nvidia/teams/morpheus/collections/morpheus_](https://catalog.ngc.nvidia.com/orgs/nvidia/teams/morpheus/collections/morpheus_). This is where a user would go if they want to use Helm charts to run Morpheus in a K8s environment.

**Describe the documentation you'd like**
This link and wording around it should be added back into the `README.md` file once we can decide on the wording to avoid potential confusion with users mixing and matching paths to get started.

**Comment by mdemoret-nv** [comment]
To be clear, this issue should separate the documentation pieces that should be seen only after release from the pieces that are seen during development. This means:

1. Remove all references of NGC and pre-built containers from the root README
2. Add the NGC references to the root of the docs/index.rst
3. Add a link to NGC in each of the releases pages
4. Ensure all version numbers match in the repo
