### ISSUE TITLE
[BUG]: In DFP, categorical columns that are numeric, get converted automatically to non-categorical numeric

### ISSUE THREAD

**Issue by Tzahi-cpacket** [nv-morpheus/Morpheus#922]
### Version

v23.01.00, branch-23.07

### Which installation method(s) does this occur on?

Docker

### Describe the bug.

I'm trying to use a numerical categorical as a feature in the morpheus DFP module. My input is json files, so that feature is coded as a string in the JSON file.  I specified it as a string in the scheme etc', but it got converted to a number by the time it got through the pipeline to the loss calculation. 

I think that that is a bug, because there are cases for categorical variables which are numeric in nature. For instance a port number. port numbers are numeric, but still categorical: "81" is not "1"  "bigger" than "80". Both "80" and "81" are just labels. 

the intended behaviour, I think, is that when a feature in the schema is specified as a string, it does not get converted to a number. 

### Minimum reproducible example

```shell
# Work from a notebook derived from morpheus/example/digital_fingerprinting/production  
# dfp_duo_training.ipynb 

# create a json file with three columns username, timestamp, FeatureA, where featureA is a 
# string with numericals like "1", "2", "81"

# It will looks something like this:

[{"username": "tom", "timestamp":1666741856,"FeatureA":"81"},
{"username": "jerry", "timestamp":1666741856,"FeatureA":"1"}]


#The feature specification would be something like:
config.ae.feature_columns = ['FeatureA']
config.ae.userid_column_name = "username"
config.ae.timestamp_column_name = "timestamp"



#The source column info would look like

source_column_info = [
    DateTimeColumn(name=config.ae.timestamp_column_name, dtype=datetime, input_name="timestamp"),
    RenameColumn(name=config.ae.userid_column_name, dtype=str, input_name="username"),
    ColumnInfo(name='featureA', dtype=str)]

#The preprocess scheme would be something like (i.e. no preprocessing)

preprocess_column_info = [
    ColumnInfo(name=config.ae.timestamp_column_name, dtype=datetime),
    ColumnInfo(name=config.ae.userid_column_name, dtype=str),
    ColumnInfo(name="FeatureA", dtype=str)]

When I now run a pipeline as in dfp_duo_trainig.ipynb, I get an error that is associated with another bug, where if there are no categorical features the loss calculation errors out (#893), so looks like my categorical featureA became a numerical featureA along the way.
```

### Code of Conduct

- [X] I agree to follow Morpheus' Code of Conduct
- [X] I have searched the [open bugs](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by dagardner-nv** [comment]
Confirmed.
I think I see at least part of the problem is how Pandas reads JSON data:
```py
import io
import json

import pandas as pd

data = [{"username": "tom", "timestamp":1666741856,"FeatureA":"81"},
        {"username": "jerry", "timestamp":1666741856,"FeatureA":"1"}]

data_s = "\n".join(json.dumps(d) for d in data)
df = pd.read_json(io.StringIO(data_s), lines=True)
print(df['FeatureA'].dtype)
```

produces:
```
int64
```

Of course the docstring for `ColumnInfo` claims it `Defines a single column and type-cast.` but that isn't happening, and the column is being passed as-is.

**Comment by dagardner-nv** [comment]
@Tzahi-cpacket I just merged a fix for this, and confirmed that the fields remain string fields. 

I did a test where I pushed your example data through DFP and this is what I got on the other end:
```json
{"timestamp":1666741856000,"username":"jerry","FeatureA":"1","origin_hash":"d6ade267f88270da2c87c79389a1550a","batch_count":1,"_row_hash":8087603799312492010,"_batch_id":1}
{"timestamp":1666741856000,"username":"tom","FeatureA":"81","origin_hash":"d6ade267f88270da2c87c79389a1550a","batch_count":1,"_row_hash":1793901708404035681,"_batch_id":1}
```
