### ISSUE TITLE
[FEA]: Replace StellarGraph library with DGL in GNN fraud detection workflow

### ISSUE THREAD

**Issue by raykallen** [nv-morpheus/Morpheus#925]
### Is this a new feature, an improvement, or a change to existing functionality?

Improvement

### How would you describe the priority of this feature request

Medium

### Please provide a clear description of problem this feature solves

I want Morpheus to use DGL instead of StellarGraph because the StellarGraph library is no longer maintained.

### Describe your ideal solution

Keep all the same functionality for GNN fraud example, but substitute DGL.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the [open feature requests](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22%2Cimprovement%2Cenhancement) and have found no duplicates for this feature request

**Comment by mdemoret-nv** [comment]
Should have been closed with #1032
