### ISSUE TITLE
[FEA] Replace `steallargraph` with an alternative library

### ISSUE THREAD

**Issue by mdemoret-nv** [nv-morpheus/Morpheus#945]
It seems that the `stellargraph` repo is dead: https://github.com/stellargraph/stellargraph. No commits or comments in the past two years. Wouldnt be too much of an issue except the pip package binds the python version to `>3.6,<3.9` which is incompatible with our version of python, 3.10.

There are a few options:

1. Install `stellargraph` using the `--ignore-python-version` flag
   1. This is the option we are using in pull #904 
1. Fork the repo and fix the required python version
   1. This seems to work since it has been done here: https://github.com/VenkateshwaranB/stellargraph
1. Change the GNN example to use an alternative library
   1. This is what we should explore in this issue

This is the original comment that prompted this issue:
> Going to stick with the pip install for now and look into replacing stellargraph in the future

_Originally posted by @mdemoret-nv in https://github.com/nv-morpheus/Morpheus/pull/904#discussion_r1190217700_

**Comment by jarmak-nv** [comment]
Hi @mdemoret-nv!
  
  Thanks for submitting this issue - our team has been notified and we'll get back to you as soon as we can!
  In the mean time, feel free to add any relevant information to this issue.

**Comment by BartleyR** [comment]
@tzemicheal This has been sitting for a while. What are the updates here?

**Comment by tzemicheal** [comment]
> @tzemicheal This has been sitting for a while. What are the updates here?

The model is prepared, I need to clean up the train/inference scripts & update the reference for the notebook, I will get back to it next week.

**Comment by mdemoret-nv** [comment]
@tzemicheal Any updates?

**Comment by mdemoret-nv** [comment]
Should have been closed with #1032
