### ISSUE TITLE
[FEA]: Add unittests for developer guide examples 

### ISSUE THREAD

**Issue by dagardner-nv** [nv-morpheus/Morpheus#994]
### Is this a new feature, an improvement, or a change to existing functionality?

Improvement

### How would you describe the priority of this feature request

Low (would be nice)

### Please provide a clear description of problem this feature solves

The code for the developer guides is currently not being tested, it would be nice to get unittests for these to ensure our documentation does not go out of date.

### Describe your ideal solution

Add tests

### Additional context

relates to #993

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the [open feature requests](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22%2Cimprovement%2Cenhancement) and have found no duplicates for this feature request

**Comment by mdemoret-nv** [comment]
Closing since tests have been added for the developer guide
